download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip","powerconsuption.zip")
data_pc<-read.table(unz("powerconsuption.zip","household_power_consumption.txt"),header=TRUE,sep=";")
head(data_pc)
data_pc$Date2<-as.Date(data_pc$Date,"%d/%m/%Y")
data_pc_02<-subset(data_pc,data_pc$Date2>='2007-02-01' & data_pc$Date2<='2007-02-02')
data_pc_02$Global_active_power<-as.numeric(as.character(data_pc_02$Global_active_power))
x<-as.numeric(nrow(data_pc_02))
dev.off()
plot(data_pc_02$Global_active_power,type="l",xlab="",xaxt="n",ylab="Global Active Power(kilowatts)")
axis(1,at=c(0,x/2,x),labels=c("Thu","Fri","Sat"))
dev.copy(png,filename="plot2.png",width=480,height=480)
dev.off()
