download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip","powerconsuption.zip")
data_pc<-read.table(unz("powerconsuption.zip","household_power_consumption.txt"),header=TRUE,sep=";")
head(data_pc)
data_pc$Date2<-as.Date(data_pc$Date,"%d/%m/%Y")
data_pc_02<-subset(data_pc,data_pc$Date2>='2007-02-01' & data_pc$Date2<='2007-02-02')
data_pc_02$Global_active_power<-as.numeric(as.character(data_pc_02$Global_active_power))
hist(data_pc_02$Global_active_power,main="Global Active Power",col="red",xlab="Global Active Power (kilowatts)",ylab="Frequency")
dev.copy(png,filename="plot1.png")
dev.off()
